### PR TITLE
Avoid object creation when invoking isDisconnectionSqlException.

### PR DESCRIPTION
**Pull request by johnou**
Motivation:

By default isDisconnectionSqlException creates a new HashSet every invocation.

Modification:

Added new package-protected method, isDisconnectionSqlCode(String sqlState), that directly checks if a given sqlState is in the internal set.

Result:

The new method improves performance by avoiding redundant object creation.

### CODE REVIEW

**Comment by johnou** [comment]
@garydgregory ptal when you have some time.

**Comment by johnou** [comment]
rebased, there was a conflict with the test class.

**Comment by garydgregory** [comment]
@johnou 

Thank you for your PR.

Please rebase on git master.

**Review by garydgregory — CHANGES_REQUESTED** [review]
Please rebase on git master.

**Pull request merged**
