### PR TITLE
[DBCP-568] ManagedConnection must clear its cached state after transaction completes

### PR DESCRIPTION
**Pull request by efge**
See [DBCP-568](https://issues.apache.org/jira/browse/DBCP-568) for details.

### CODE REVIEW

**Comment by efge** [comment]
A unit test is now included.

**Comment by garydgregory** [comment]
@psteitz Seems ok to me, ok with you?

**Comment by garydgregory** [comment]
> @psteitz Seems ok to me, ok with you?

@rmannibucau any thoughts?

**Comment by garydgregory** [comment]
> > @psteitz Seems ok to me, ok with you?
> 
> @rmannibucau any thoughts?

Ping @rmannibucau

**Pull request merged**
