### PR TITLE
DBCP-589 - Provide Jakarta namespace ready artifact of DBCP2

### PR DESCRIPTION
**Pull request by rzo1**
# What does this PR do?

This PR provides a Jakarta namespace ready artifact of DBCP2 by relocating the related `javax.transcation.*` imports to  `jakarta.transaction.*` and provides a related (attached) artifact with a jakarta classifier to be consumed by user projects.

### CODE REVIEW

**Comment by garydgregory** [comment]
While clever, this feels like a hack, untested as well. We should update the sources when we want to do this. We can't even tell if such a change would break binary compatibility.

**Comment by rzo1** [comment]
If we change the source code (which is indeed an option), it might be required to maintain two versions of dbcp2 as the javax namespace while be around for a long time. In the end, it would be great to have a Jakarta-ready version of DBCP2 available - otherwise, people are forced to do some "hacky" things to achive that. 

I cannot follow regarding "binary compatibility" - maybe you can explain that point a bit more?

**Comment by rmannibucau** [comment]
+1 to get it in or switch now (I know it is a bit early and it is not justified to get 2 "main" branches).
Note that if it helps adding a test is very feasible - we do at openwebbeans for ex - and enforcing binary compatiblity can be done too even if quite useless for this particular project (guess a test is a very good compromise since it will validate both at once).

The only change I would do is to relocate `org.apache.commons.dbcp2` in `org.apache.commons.dbcp2.jakarta` to ensure both can run together - yes it happens.

**Comment by garydgregory** [comment]
Please, no, -1; impossible to debug, and again, untested, also we ideally should have a consistent way to deal with Jakarta naming throughout Apache Commons, and the sanest way to do that is changing the source, if that breaks binary compatibility, then it can be done in a major version.

**Comment by rzo1** [comment]
@garydgregory So let's start a discussion on dev@ how the Commons wants to deal with Jakarta?

**Comment by rmannibucau** [comment]
> impossible to debug, and again, untested

So factually you can debug as any artifact - you shade the sources too, it is used and got proven working fine by multiple asf projects.
And test is just a matter of writing some test or re-executing the suite ones if you prefer (but technically/theorically speaking you need just a smoke test covering the javax integration code to ensure it works since functionally the rest is already covered).

So overall both points are not blockers and are even almost not true.

> the sanest way to do that is changing the source

So it means jakarta is used on master, by commons rules it becomes dbcp3.
So, as mentionned question is: do we abandon dbcp2 and consider javax is no more used. If so I join you but if not (and I think we still have 2-3 years of javax) then we should target to enable jakarta (dbcp2.jakarta package) and maintain a single code base - would be a pain for no gain at all to fork ourselves for that.

**Comment by rzo1** [comment]
Closing, see  https://lists.apache.org/thread/kzoox2hkb484gyj1z13rn42xko2bp29w for details.

**Pull request closed without merging**
