### PR TITLE
Seems a trivial change to me, should I create a Jira?

### PR DESCRIPTION
**Pull request by JacquesLeRoux**
In OFBiz we implemented DebugManagedDataSource

http://svn.apache.org/viewvc/ofbiz/ofbiz-framework/trunk/framework/entity/src/main/java/org/apache/ofbiz/entity/connection/DebugManagedDataSource.java?view=markup

We had to write DebugManagedDataSource::close in order to avoid throwing an InterruptedException

‘ManagedDataSource’ should declare more specific exceptions than ‘Exception’ for the ‘close’ method to allow the compiler to check that no ‘InterruptedException’ are thrown.

### CODE REVIEW

**Comment by JacquesLeRoux** [comment]
Oops, this merge fixes a typo (missed a comma :/)

**Comment by garydgregory** [comment]
@JacquesLeRoux 

Thank you for your patch. 

Yes, we need a JIRA for changes like this. 

While you are at it, why not add Javadocs to this method to set expectations?

Gary

**Comment by garydgregory** [comment]
You can also then update the `changes.xml` file.

**Comment by JacquesLeRoux** [comment]
I created https://issues.apache.org/jira/browse/DBCP-539 for that

**Pull request merged**
