### PR TITLE
refactor: use ReentrantLock in PoolableConnection.close (#DBCP-591)

### PR DESCRIPTION
**Pull request by cortlepp-intershop**
This PR removes synchronized from `PoolableConnection.close()` and replaces it by a `ReentrantLock` which is owned by the connection. I could not find any references in the code which externally synchronize on this connection, so I think that not other changes are necessary.

This closes [#DBCP-591](https://issues.apache.org/jira/browse/DBCP-591).

### CODE REVIEW

**Comment by cortlepp-intershop** [comment]
Hey @garydgregory any thoughts?

**Comment by garydgregory** [comment]
> Hey @garydgregory any thoughts?

Hello @cortlepp-intershop 
There is no test to prove this fixes anything.

**Comment by cortlepp-intershop** [comment]
True, but do you have a suggestion on how to write such a test? Since the Issue is not that something doesn't work, it's rather a performance thing. The current implementation, because it uses `synchronized` and then does some I/O, doesn't work "gracefully" with the new VirtualThreads introduced in JDK 21 in the sense that the JVM cannot unmount the VirtualThread during this I/O operation. This doesn't break anything in a functional sense, it just impacts the scheduling (and therefore the throughput) of the application negatively. Using a `ReentrantLock` fixes this because, unlike `synchronized`, it does not prevent the JVM from unmounting the VirtualThread during this I/O operation.

In the discussion on the [linked issue](https://issues.apache.org/jira/browse/DBCP-591) Phil Steitz also suggested that locking on this method might not be necessary at all, but since he wasn't sure I implemented the "safe" version using the alternative locking mechanism.

In order to test that this works, my only idea would be to start the test runner with the JVM property `-Djdk.tracePinnedThreads=full`, and the assert that no pinning stacktrace is present in the log. But this seems to me to be very brittle, hard to implement and also somewhat overkill for the situation at hand.

**Comment by garydgregory** [comment]
Hello @psteitz ?
Any thoughts on whether we should bring in this PR? How can we make sure that this does make things worse and in fact better on Java 8, 11, 17, and 21? Is there a JMH benchmark that would make sense to write?

**Comment by psteitz** [comment]
Sorry for the very slow response.  I think this is good to merge.  I agree tests would be nice, but like the OP, I can't think of a simple way to demonstrate the impact of the pinning, which is pretty certain to happen on the (not normal) execution paths where connections get physically closed.  This should have no impact on performance in earlier JDKs.  I also verified that no other code relies on this object's monitor.

**Comment by garydgregory** [comment]
The build is broken.

**Comment by psteitz** [comment]
Crap.  Forgot to check checkstyle output.  Seems a formatting nit.  Will
fix in a few hours.

**Pull request merged**
