### PR TITLE
[DBCP-484] Connection leak during XATransaction in high load

### PR DESCRIPTION
**Pull request by zhfeng**
The race condition is in the ManagedConnection when closing the
connection. This could case the connection leak during the transaction
in high load.

### CODE REVIEW

**Comment by zhfeng** [comment]
Thank @markt-asf for reviewing and I've changed to use the private lock. Also add some comments to make clearer.

**Comment by PascalSchumacher** [comment]
@markt-asf Is this ready to merge?

**Comment by markt-asf** [comment]
Looks good to me

**Comment by zhfeng** [comment]
@garydgregory can it be include in the new release ?

**Comment by garydgregory** [comment]
Hi @zhfeng,

The release VOTE for 2.3.0 based on RC1 just got underway. If the VOTE passes, this PR will have to be considered for the next release after that.

Also, to be honest, I had forgotten about this PR :-( 

Note that the fact this PR does not contain a unit test makes it less likely for consideration.

Ideally, we would like a unit test that fails without the main patch. Then after applying the main patch, the unit test passes.

**Comment by zhfeng** [comment]
Thanks @garydgregory , I'm working on the unit test by using the byteman tool which is LGPL. So it is OK to use it just in the tests ?

**Comment by garydgregory** [comment]
Why not write a real test using an H2 database? http://www.h2database.com/html/main.html

**Comment by garydgregory** [comment]
WRT byteman, I am not 100% sure if it is OK to link to it from test code. That will need some research from someone on the Apache side.

**Comment by markt-asf** [comment]
Thanks for the updated PR. I was thinking sync on new Object() but a Lock is fine too. Looks good to me.

**Comment by garydgregory** [comment]
LGPL 2.1 is listed here https://www.apache.org/legal/resolved.html under "WHICH LICENSES MAY NOT BE INCLUDED WITHIN APACHE PRODUCTS?"

**Pull request closed without merging**
