### PR TITLE
DBCP-585 PR for idea clarification

### PR DESCRIPTION
**Pull request by kurtcebe**

### CODE REVIEW

**Comment by kurtcebe** [comment]
CI failed as source file length check reported 6 lines over the limit. I've amended PR to make the source file shorter.

**Comment by garydgregory** [comment]
[DBCP-585](https://issues.apache.org/jira/browse/DBCP-585)

**Comment by garydgregory** [comment]
Hi @kurtcebe 
There are test failures in the GitHub builds.

**Comment by kurtcebe** [comment]
Hi @garydgregory thanks for the heads up , I've updated the PR.

**Comment by kurtcebe** [comment]
@garydgregory  I'm guessing this is happening due to unit tests running in parallel, which was already highlighted in a TODO comment at another test method [here](https://github.com/apache/commons-dbcp/blob/14d3df96d27068b5819863aede83de9125b11021/src/test/java/org/apache/commons/dbcp2/TestBasicDataSource.java#L623). I've followed suit by just adding the same comment, but now I'm thinking, maybe that was unnecessarily optimistic. Since we're using PlatformMBeanServer in our tests without mocking, all tests are registering/unregistering Means on a singleton, hence we may be seeing side effects from other tests running with different JMX config.  I'll take another look into this to verify this. Thanks for your time as always.

**Comment by kurtcebe** [comment]
I've removed the test to check the default state (i.e. we don't disable connection MBean). It turns out that the initial states are different for different types of Datasources, for example, BasicManagedDatasource does not register connection by default, while BasicDatasource and PStmtPoolingBasicDatasource does, i.e. there is no common value to check. We still test the case when parameter is set.

**Pull request merged**
