### PR TITLE
WIP DBCP-509: Consistency across methods in PerUserPooldataSource and its parent

### PR DESCRIPTION
**Pull request by kinow**
For discussion for DBCP-509. A proposal to use primitives and use the default values instead of nulls, as in the other methods.

### CODE REVIEW

**Comment by kinow** [comment]
If this change is approved, then I'd update the test code from DBCP-504 later :+1:

**Comment by garydgregory** [comment]
-1 for 2.x as this patch breaks BC :-( See 'mvn clirr:check'.

**Comment by garydgregory** [comment]
@kinow May you please rebase on master? I'd like to see if the default goal in the POM properly causes the build to fail if JApiCmp fails.

**Comment by garydgregory** [comment]
@kinow 
Closing since it breaks BC and there is no further activity.

**Comment by kinow** [comment]
No worries @garydgregory . Had completely forgotten about it, but no bandwidth to work on this issue now. We can revisit it later on :+1: Thanks!

**Pull request closed without merging**
